###########################################################
### Welcome to Beautiful Jekyll!
###########################################################

############################
# --- Required options --- #
############################

title: Eunmi Cho
author: Eunmi Cho

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  CV: "cv"
  Research: "research"

################
# --- Logo --- #
################

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "eunmicho@yonsei.ac.kr"

###########################
# --- General options --- #
###########################

url-pretty: "cho-eunmi.github.io"

title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false

######################################
# --- Colours / background image --- #
######################################

page-col: "#F0F6FF"
text-col: "#1C3557"
link-col: "#1C6EA4"
hover-col: "#A8C8E8"
navbar-col: "#1C3557"
navbar-text-col: "#FFFFFF"
navbar-border-col: "#122540"
footer-col: "#1C3557"
footer-text-col: "#A8C8E8"
footer-link-col: "#FFFFFF"
footer-hover-col: "#A8C8E8"

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

timezone: "Asia/Seoul"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
